# Pipeline Configuration

# Path to the folder containing the fasta format allele sequences
ALLELE_FASTA_FOLDER: /path/to/folder/containing/alleles

# Path to the genome fasta file to be used for mapping/alignment
# The location of this file should be writable so that indexes can be created
GENOME: /path/to/genome.fasta

# Path to barcode fasta file used for demultiplexing
BARCODES: /path/to/barcodes.fasta

# path to the gene definition file
LOCI:
  - /path/to/gene_1.yaml
  - /path/to/gene_2.yaml
  - /path/to/gene_N.yaml

# path to the experiment definition file
EXPERIMENT: /path/to/experiment.yaml
