channels:
  - bioconda
dependencies:
  - python=3.5
  - drmaa=0.7
  - snakemake=3.11.2
  - pybedtools=0.7.10
  - pip:
    - "git+https://wgallard@git.lumc.nl/PharmacogenomicsPipe/variant_tools.git@master#egg=variant_tools-master"
