channels:
  - bioconda
dependencies:
  - python=3.5
  - drmaa=0.7
  - snakemake=3.13.3
  - pybedtools=0.7.10
  - pip:
    - "git+https://wgallard@git.lumc.nl/PharmacogenomicsPipe/variant_tools.git@master#egg=variant_tools-master"
    - "git+https://git.lumc.nl/PharmacogenomicsPipe/pipe_runner.git@master#egg=pipe_runner"
