channels:
  - bioconda
dependencies:
  - python=3.5
  - drmaa=0.7
  - snakemake=3.11.2
  - biopython=1.69
  - edlib=1.1.2
  - pip:
    - "--editable git+https://wgallard@git.lumc.nl/PharmacogenomicsPipe/variant_tools.git#egg=variant-tools"

